process.on('uncaughtException', (error) => {

    console.error('Caught exception', error);
});
